Feature/18 switchable sides
DigKick/DigKick pull request #60
Opened 2024-09-18 20:54 UTC by hiqs-chris

Fixes #18

2024-10-07 23:31 UTC, makoeta commented
Hallo,

ist "name" bei Team nicht überflüssig? 🤔

2024-10-08 00:01 UTC, makoeta requested changes
Joa, hab von paar viel Sachen noch nie vorher gehört.
Wäre wahrscheinlich am besten wenn @d3473r drüber schaut.

Der einzige breaking Fehler, der mir aufgefallen ist:
Wenn man im dev mode die Teams dreht, drehen sich nicht die +/- dev buttons nicht mit. Man ändert dann den Score für die andere Seite

2024-10-18 20:44 UTC, hiqs-chris commented on frontend/libs/game/src/lib/game/game-score/game-score.component.stub.ts
.stub Dateien sind dummy-Komponenten. Wenn du also Tests bei anderen Komponenten schreibst, diese aber andere Komponenten einbindet, kannst du stattdessen die StubComponent Variante nutzen. Durch den selben selector funktioniert es, musst aber nicht mit der Logik von den Abhängigkeiten dealen

2024-10-18 20:45 UTC, hiqs-chris commented on backend/src/database/modules/team/teamEntity.ts
> +  name!: string;
Dachte irgendwie, dass es nice wäre einen echten Namen zu haben. Beispielsweise bei Turnieren bestimmt irgendwann relevant, aber hierfür war es glaub unnötig. Mache es rückgängig

2024-10-18 20:47 UTC, hiqs-chris commented on frontend/src/index.html
> +    <meta
Weil es den meta-Tag doppelt gab. Hab es nur vereint

2024-10-18 20:53 UTC, hiqs-chris commented on backend/src/models/game.ts
> +    this.teamWhite = new Team('White', TeamColor.WHITE);
Name von Team wieder entfernt

2024-10-18 21:07 UTC, hiqs-chris commented on frontend/src/assets/images/sprite.png
Converted

2024-10-18 21:11 UTC, hiqs-chris commented on frontend/libs/game/src/lib/game/game-score/game-score.component.scss
Deleted

2024-10-18 21:29 UTC, hiqs-chris commented
@makoeta Alle Kommentare sollten resolved sein. Auch den hauptsächlichen Fehler, dass die Score-Buttons nicht mit geswaped werden, habe ich behoben.
Weiter Tests kann man mit der Zeit machen. Viele Komponenten sind aktuell nur UI und haben kaum Funktionen. Lohnt also nicht wirklich.

2024-10-18 21:29 UTC, hiqs-chris commented
Hier mal ein Screenshot, wie die UI mit diesen Änderungen aussieht

<img width="1507" alt="Bildschirmfoto 2024-10-18 um 23 25 38" src="https://github.com/user-attachments/assets/d107905e-8884-4e88-86de-82ce9b8f7a5b">

2024-10-25 20:19 UTC, d3473r approved these changes

2024-10-25 20:19 UTC, makoeta approved these changes

2024-10-25 20:24 UTC, merged